before_install:
    - travis_retry sudo add-apt-repository -y ppa:jgross-h/many-coq-versions
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install coq-8.5pl3
script:
    - make
sudo: required
